[build]
  command = "echo \"Hello world!\""
  publish = "dist/"

[[plugins]]
  package = "@helloample/netlify-plugin-replace"

[context.main.environment]
  SITE_TITLE = "Netlify Plugin Replace Demo"
  APP_ENDPOINT = "https://ample.co"
  REDIR_ROLE = "admin"